[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "llmvalidate"
version = "0.4.2"
description = "Oncoshot LLM validation framework"
readme = "readme.md"
requires-python = ">=3.11"
dependencies = [
    "pandas>=3.0.0",
    "numpy>=2.4.1",
    "pydantic>=2.12.5",
    "tqdm>=4.67.1",
    "python-dateutil>=2.9.0",
    "pytest>=9.0.2",
    "colorama>=0.4.6"
]
license = { text = "MIT" }

classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "License :: OSI Approved :: MIT License",
  "Intended Audience :: Developers"
]

[project.urls]
"Homepage" = "https://github.com/Oncoshot/llm-validation-framework"
"Repository" = "https://github.com/Oncoshot/llm-validation-framework"
"Bug Tracker" = "https://github.com/Oncoshot/llm-validation-framework/issues"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["llmvalidate*"]
exclude = ["tests*", "docs*", "scripts*"]

[tool.pytest.ini_options]
pythonpath = [
  "src",
]

[tool.semantic_release]
version_variable = ["src/llmvalidate/__init__.py:__version__"]
version_toml = ["pyproject.toml:project.version"]
branch = "master"
allow_zero_version = true
build_command = "pip install build && python -m build"
upload_to_pypi = true
upload_to_release = true
commit_version_number = true


